Dev algorithm
bellshade/OpenSeries pull request #55
Opened 2024-02-06 18:27 UTC by kayabaakihiko13

## Deskripsi (Description)

## Checklist:

### Umum:

- [x] Saya menambah fungsi / algoritma.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:

- [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/OpenSeries/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
- [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

### Unit Testing dan Linting (wajib):

- [x] pytest
- [x] pre-commit

## Environment

Saya menggunakan (I'm using):

- `os` = `linux (ubuntu Distro)`
- `python` = `python3.11.6 `

linked issue #NOMOR_ISSUE

2024-02-06 18:47 UTC, slowy07 requested changes

2024-02-06 18:47 UTC, slowy07 commented on OpenSeries/matematika.py
> +    return round(result * delta)
```suggestion
def integral(
    f: Callable[[float], float], a: float, b: float, iterable: int = 4
) -> Union[float, error.errorTipeData]:
    """
    integral merupakan suatu konsep yang merupakan operasi kebalikan dari diferensiasi.
    Integral memiliki dua bentuk utama: integral tak tentu (indefinite integral)
    dan integral tentu (definite integral).
    Args:
        f (Callable[[float],float]): fungsi input
        a (float): nilai awal
        b (float): nilai atas
        iterable (int, optional): mengatur putaran. Defaults to 4.

    """
    if not all(isinstance(data, float) for data in [a, b]):
        return error.errorTipeData(["float"])
    if not isinstance(iterable, int):
        return error.errorTipeData(["int])
    delta = (b - a) / iterable
    result = 0.5 * (f(a) + f(b))
    for i in range(1, iterable):
        result += f(a + i * delta)
    return round(result * delta)
```

2024-02-07 05:06 UTC, slowy07 requested changes
tambahkan unittesting untuk mengetest dari fungsi, jika user memasukkan tipe data yang salah

2024-02-07 06:07 UTC, kayabaakihiko13 commented
> tambahkan unittesting untuk mengetest dari fungsi, jika user memasukkan tipe data yang salah

done bang

2024-02-07 11:25 UTC, slowy07 approved these changes
LGTM 💯

2024-02-07 11:26 UTC, merged